//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFSample
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookLendingDetail
    {
        public int BookLendingDetailsID { get; set; }
        public int BookID { get; set; }
        public int MemberID { get; set; }
        public System.DateTime DueDate { get; set; }
        public int IsReturned { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Member Member { get; set; }
    }
}
